name:                weight-recorder
version:             0.1.0.0
github:              "shinofumijp/weight-recorder"
license:             BSD3
author:              "shinofumijp"
maintainer:          "fumiya.shinozuka@finc.com"
copyright:           "2019 shinofumijp"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/shinofumijp/weight-recorder#readme>

dependencies:
- base >= 4.7 && < 5
- bcrypt
- bytestring
- filepath
- HDBC
- HDBC-sqlite3
- http-types
- Spock
- mustache
- persistable-record
- relational-query-HDBC
- relational-query
- text
- time

library:
  source-dirs: src/
  ghc-options: -Wall
